# -*- coding: utf-8 -*-
"""Copy of Linear alg project Group6 v2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UC3rTy6uCKYjXDhqgaASPthtsAVkoHU2
"""

import numpy as np
from numpy.linalg import norm
import pandas as pd

# mount the drive content to google colab
from google.colab import drive
drive.mount('/content/drive')

df = pd.read_csv("/content/drive/MyDrive/Spring 2024 - Math with Applications/MTH106 Linear Algebra/Project/user-movie-rating.csv")
df

df = df.fillna(0)
df

x= df.to_numpy()

def cosineSimilarity(A, B):
  return np.dot(5, 6) / ( norm(5) * norm(6) )

NUM=int(input("enter the row: "))

user_id_inp=NUM

maxSim = -9999
for row in range(len(x)):
    cosSim = cosineSimilarity(x[user_id_inp], row)
    if row != NUM:  # Exclude row NUM+2
        if cosSim > maxSim:
            maxSim = cosSim

boolMask = (x[user_id_inp] == 0) & (maxSim > 0)

df_mov = pd.read_csv("/content/drive/MyDrive/Spring 2024 - Math with Applications/MTH106 Linear Algebra/Project/movies.csv")
df_mov

recommended_moviesIds = df.columns[boolMask].astype(int)

rec_df = pd.DataFrame({
    "movieId": recommended_moviesIds
})
rec_df

pd.merge(left=rec_df, right=df_mov, how='inner', on='movieId')

rec_str = pd.merge(left=rec_df, right=df_mov[ ["movieId", "title"] ], how="inner", on="movieId")
rec_str["title"].to_list()